# Generated by Django 2.2 on 2020-09-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Army Number')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('rank', models.CharField(blank=True, choices=[('L/Nk', 'L/Nk'), ('Sep', 'Sep'), ('Nk', 'Nk'), ('Hav', 'Hav'), ('Nb Sub', 'Nb Sub'), ('Sub', 'Sub'), ('SM', 'SM'), ('H/Lt', 'H/Lt'), ('Lt', 'Lt'), ('Capt', 'Capt'), ('Maj', 'Maj'), ('Lt Col', 'Lt Col'), ('Col', 'Col'), ('Brig', 'Brig'), ('Maj Gen', 'Maj Gen'), ('Lt Gen', 'Lt Gen')], max_length=20, null=True)),
                ('i_card_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='I-Card Number')),
                ('trade', models.CharField(blank=True, choices=[('MT', 'MT'), ('SKT', 'SKT'), ('SHT', 'SHT'), ('H/Keeper', 'H/Keeper'), ('Washerman', 'Washerman'), ('Cook Chef', 'Cook Chef'), ('Carpenter', 'Carpenter'), ('Clk SD', 'Clk SD')], default='trade', max_length=15, null=True)),
                ('company', models.CharField(blank=True, choices=[('HQ Coy', 'HQ Coy'), ('A Coy', 'A Coy'), ('B Coy', 'B Coy'), ('C Coy', 'C Coy'), ('D Coy', 'D Coy'), ('LRW', 'LRW')], default='trade', max_length=15, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('wpn_type', models.CharField(blank=True, choices=[('LMG 7.76mm', 'LMG 7.76mm'), ('INSAAS 5.56mm', 'INSAAS 5.56mm'), ('CMG 9mm', 'CMG 9mm')], max_length=15, null=True, verbose_name='Wpn Type')),
                ('regd_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Regd. Number')),
                ('butt_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Butt Number')),
                ('issue_type', models.CharField(blank=True, choices=[('OD', 'OD'), ('TD', 'TD'), ('Attachment', 'Attachment')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Initial Data Entry',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_out', models.CharField(max_length=6)),
                ('weapon_in', models.CharField(blank=True, max_length=6, null=True)),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_data_entry.InitialDataEntry')),
            ],
            options={
                'verbose_name': 'IN-OUT',
            },
        ),
    ]
